[2024-08-09T01:43:21.691+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-09T01:43:21.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-08-09T01:43:20.701685+00:00 [queued]>
[2024-08-09T01:43:21.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-08-09T01:43:20.701685+00:00 [queued]>
[2024-08-09T01:43:21.703+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-09T01:43:21.708+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-08-09 01:43:20.701685+00:00
[2024-08-09T01:43:21.712+0000] {standard_task_runner.py:64} INFO - Started process 79 to run task
[2024-08-09T01:43:21.714+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-08-09T01:43:20.701685+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpvrhenadd']
[2024-08-09T01:43:21.716+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask reddit_extraction
[2024-08-09T01:43:21.749+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-08-09T01:43:20.701685+00:00 [running]> on host 172cf4fb9077
[2024-08-09T01:43:21.789+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Varun MJ' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T01:43:20.701685+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-09T01:43:20.701685+00:00'
[2024-08-09T01:43:21.790+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-09T01:43:21.798+0000] {logging_mixin.py:188} INFO - Connected to reddit!
[2024-08-09T01:43:22.581+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-09T01:43:22.582+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'selftext'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 16, in reddit_pipeline
    post_df = transform_data(post_df)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/reddit_etl.py", line 45, in transform_data
    post_df['selftext'] = post_df['selftext'].astype(str)
                          ~~~~~~~^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'selftext'
[2024-08-09T01:43:22.609+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-08-09T01:43:20.701685+00:00, execution_date=20240809T014320, start_date=20240809T014321, end_date=20240809T014322
[2024-08-09T01:43:22.652+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 33 for task reddit_extraction ('selftext'; 79)
[2024-08-09T01:43:22.704+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-09T01:43:22.716+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-09T01:43:22.716+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
